### ISSUE TITLE
Do I need to deploy this app?

### ISSUE THREAD

**Issue by agahkarakuzu** [openjournals/reviewers#3]
Hi @xuanxu, sorry for pinging you quite a bit in the last few days. 

I am trying to understand if I need to deploy this app because following ENV vars exist in the buffy production settings:

```yaml
    reviewers_host_url: <%= ENV['REVIEWERS_HOST_URL'] %>
    reviewers_api_token: <%= ENV['REVIEWERS_API_TOKEN'] %>
 ```

And I see `ojra` is required in the GemFile. 

I am repurposing and deploying these apps for NeuroLibre, but it is not an OpenJournals members, so I am not even sure if asking for the host URL and the API token is feasible. 

If I do not include this app would buffy become completely dysfunctional, or would it still be functional with less features?

**Comment by xuanxu** [comment]
Hi @agahkarakuzu!
No, you don't need it. This is an application JOSS uses to manage the reviewers, and so we have a custom responder for the bot to comunicate (using the ojra gem) with this app everytime a reviewers is assigned to a submission. Is that responder the one that uses those two ENV vars. So, you don't need to deploy the Reviewers app, ojra or configure those ENV vars.
And unless you really want to use any of the custom responders in the openjournals folder I suggest you base your bot code in the `main` branch of the buffy repo.
